### PR TITLE
Add small caps in html

### PR DESCRIPTION
**Pull request by manuelguzmandao**
I've added small caps for an own need. Just thought you could use this if that fits your roadmap. I tried to update related tests as well, but could not make them run to verify them.

### CODE REVIEW

**Comment by ShayHill** [comment]
That's awesome. Thank you. I do plan to support additional style tags, so this is useful and appreciated.


-------- Original message --------
From: manuelguzmandao ***@***.***>
Date: 3/15/21 6:12 PM (GMT-06:00)
To: ShayHill/docx2python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShayHill/docx2python] Add small caps in html (#14)


I've added small caps for an own need. Just thought you could use this if that fits your roadmap. I tried to update related tests as well, but could not make them run to verify them.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ShayHill/docx2python/pull/14

Commit Summary

  *   feat: add small caps in html
  *   feat: add small caps in html

File Changes

  *   M docx2python/text_runs.py<https://github.com/ShayHill/docx2python/pull/14/files#diff-1316d01e3f63b02036a9a643bd1c1c93654184e1d4f5d321ec64c9de1cdb4661> (4)
  *   M test/test_text_runs.py<https://github.com/ShayHill/docx2python/pull/14/files#diff-0a1ef158f961422a30f386845c3291c97b348590b90806eccfaf4634ee923e1c> (11)

Patch Links:

  *   https://github.com/ShayHill/docx2python/pull/14.patch
  *   https://github.com/ShayHill/docx2python/pull/14.diff

**Comment by manuelguzmandao** [comment]
Good to hear!! Let me know when you plan to merge and publish so I can switch back to the official published package ;)

**Comment by manuelguzmandao** [comment]
Hello there,
I've just added additional cases for numbered lists. The code is as ugly as the spaghetti in the xml files :( use cases are pretty bad with styles coming back and forth between numbering.xml and style.xml

**Comment by ShayHill** [comment]
I'm going to have a closer look at this after I wrap up Docx2Python 2.0. Thank you.

**Pull request closed without merging**
