### PR TITLE
fix typing hints to include io.BytesIO

### PR DESCRIPTION
**Pull request by conitrade-as**

### CODE REVIEW

**Comment by ShayHill** [comment]
This looks good. Can you provide a test calling docx2python with an io.BytesIO object?

**Comment by conitrade-as** [comment]
There was a simple test added which loads the .docx from a BytesIO object.

**Comment by ShayHill** [comment]
Thank you! I will pull later today.

**Comment by ShayHill** [comment]
Merged on PyPi in 2.3.0

**Pull request merged**
