### PR TITLE
To make extraction of images optional

### PR DESCRIPTION
**Pull request by royn5618**
I was trying to load images but I am getting this error - BadZipFile: Bad CRC-32 for file 'word/media/image3.png'.

So I tried to make extraction of images optional because in my case, I do not want the images. I will just be working with texts.

Thanks!

### CODE REVIEW

**Comment by ShayHill** [comment]
Hey, Roy. That looks great. Will be a few days till I’m able to take a close look and run tests. Thank you.

-Shay

**Comment by royn5618** [comment]
Thanks! Would be of great help.

**Comment by royn5618** [comment]
Thanks. Right!
Should I update the ReadMe?

**Comment by royn5618** [comment]
Updated the code. Please check. Thanks!

**Comment by ShayHill** [comment]
Merged. Thank you, Roy.

**Comment by ShayHill** [comment]
I'm afraid it will be Wednesday before I'm able to update pypi.

**Comment by royn5618** [comment]
That's okay. Thanks a million!

**Comment by ShayHill** [comment]
On Pypi as 1.1.100.

Thank you again for the contribution.

**Comment by royn5618** [comment]
Thanks!
Nabanita

**Pull request merged**
